# Generated by Django 4.1.7 on 2023-03-05 11:23

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('trailer_link', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=200)),
                ('duration', models.IntegerField()),
                ('age_category', models.SmallIntegerField()),
                ('cast', models.TextField()),
                ('release_date', models.DateField()),
                ('direction', models.CharField(max_length=200)),
                ('script', models.CharField(max_length=200)),
                ('poster', models.ImageField(upload_to=movies.models.poster_filepath)),
            ],
        ),
    ]
