# Generated by Django 4.1.7 on 2023-03-06 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('price', models.FloatField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='movies.moviemodel')),
            ],
        ),
        migrations.CreateModel(
            name='SeatsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats_numbers', models.CharField(max_length=100)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='movies.programmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TicketsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='movies.programmodel')),
                ('seats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.seatsmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
