# Generated by Django 4.1.7 on 2023-03-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_programmodel_seatsmodel_ticketsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='trailer_link',
            field=models.URLField(),
        ),
    ]
