# Generated by Django 4.1.7 on 2023-03-17 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0003_alter_moviemodel_trailer_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmodel',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.moviemodel'),
        ),
        migrations.AlterField(
            model_name='seatsmodel',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.programmodel'),
        ),
        migrations.AlterField(
            model_name='ticketsmodel',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.programmodel'),
        ),
        migrations.AlterField(
            model_name='ticketsmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
