# Generated by Django 4.1.7 on 2023-03-25 10:33

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_programmodel_movie_alter_seatsmodel_program_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=movies.models.poster_filepath),
        ),
    ]
